### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by delfick**
I've made the vendored packages install_requires and added some decode('utf-8') and fixed print statements in pre-commit.

### CODE REVIEW

**Comment by andrewgross** [comment]
Thanks for sending this over, I will review it shortly!

**Comment by delfick** [comment]
cool cool :)

Any update on this ?

**Comment by andrewgross** [comment]
Sorry totally forgot. Will tackle it tomorrow.

**Comment by delfick** [comment]
excellent :)

**Comment by andrewgross** [comment]
Why do we want to move away from vendored packages?  Is this the only way to get python3 working properly?

**Comment by delfick** [comment]
I couldn't work out where you were getting elementtree code from and
requests is a very stable library.

**Comment by andrewgross** [comment]
The main reason I vendored the requests code is so that it wouldnt conflict with any version the user might be using already, on the fence about it.

**Comment by delfick** [comment]
Fair enough. Feel free to vendor it again.

**Comment by delfick** [comment]
Do you want me to repush with requests vendored?
(this pull request is blocking me releasing the next version of my application (http://bespin.readthedocs.org/))

**Comment by andrewgross** [comment]
Yes lets try that.  I was messing around with trying to unvendor `elementtree` but lock a specific version, which seems hopeless.

**Comment by andrewgross** [comment]
Sorry for being so behind on this, very busy moving the last couple of weeks.  I am going to merge this in to master and bump the major version number for now.

**Comment by andrewgross** [comment]
Version 0.8.0 released with python3 support, let me know how it goes @delfick

**Comment by delfick** [comment]
Yay! Thankyou so much :)

I hope your move went well.

Got a busy day today, but I should get around to making a pull request
vendoring requests later on if you still want.

**Pull request merged**
